apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: product
  description: Product
spec:
  type: team
  profile:
    displayName: Product
    email: product@example.com
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=Loki&backgroundType=gradientLinear&backgroundColor=b6e3f4,ffd5dc,ffdfbf,c0aede
  parent: backoffice
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: dinni
spec:
  profile:
    displayName: Dinni
    email: dinni@ciptadrasoft.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Bear&backgroundColor=transparent
  memberOf: [product]